package:
  name: torchvision
  version: "{{ environ.get('TORCHVISION_BUILD_VERSION') }}"

source:
 path: "{{ environ.get('TORCHVISION_GITHUB_ROOT_DIR') }}"

requirements:
  build:
    - {{ compiler('c') }} # [win]

  host:
    - python
    - setuptools
{{ environ.get('CONDA_PYTORCH_CONSTRAINT') }}
{{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}

  run:
    - python
    - pillow >=4.1.1
    - numpy >=1.11
    - six
{{ environ.get('CONDA_PYTORCH_CONSTRAINT') }}
{{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}

build:
  number: {{ environ.get('TORCHVISION_BUILD_NUMBER') }}
  string: py{{py}}_cu{{ environ['CUDA_VERSION'] }}_{{environ.get('TORCHVISION_BUILD_NUMBER')}}
  script: python setup.py install --single-version-externally-managed --record=record.txt # [not win]
  script_env:
    - CUDA_VERSION
  features:
{{ environ.get('CONDA_CPU_ONLY_FEATURE') }}

test:
  imports:
    - torchvision
    - torchvision.datasets
    - torchvision.transforms
  source_files:
    - test
  requires:
    - pytest
    - scipy
  commands:
    pytest .


about:
  home: https://github.com/pytorch/vision
  license: BSD
  license_file: LICENSE
  summary: 'image and video datasets and models for torch deep learning'
